/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analogsection;
import java.awt.CardLayout;
import java.awt.LayoutManager;

/**
 *
 * @author John
 */
public class WoodInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form WoodInfoPanel
     */
    public WoodInfoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLbl = new javax.swing.JLabel();
        BackNextLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        BackgroundLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MenuBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setLayout(null);

        TitleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TitleLbl.setForeground(new java.awt.Color(255, 255, 255));
        TitleLbl.setText("This is the section for the wood info");
        add(TitleLbl);
        TitleLbl.setBounds(60, 50, 300, 22);

        BackNextLbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\John\\Desktop\\resize.png")); // NOI18N
        add(BackNextLbl);
        BackNextLbl.setBounds(260, 320, 120, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\John\\Desktop\\download (3).jpg")); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(100, 80, 230, 220);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Oak Tree:");
        add(jLabel3);
        jLabel3.setBounds(60, 330, 60, 17);

        jTextField1.setText("Strong, Resistent and hard");
        add(jTextField1);
        jTextField1.setBounds(120, 330, 160, 30);

        BackgroundLbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\John\\Desktop\\Wood-Background-Texture-452x336.jpg")); // NOI18N
        add(BackgroundLbl);
        BackgroundLbl.setBounds(0, 40, 400, 300);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\John\\Desktop\\Wood-Background-Texture-452x336.jpg")); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 340, 400, 100);

        MenuBtn.setText("Main Menu");
        MenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBtnActionPerformed(evt);
            }
        });
        add(MenuBtn);
        MenuBtn.setBounds(270, 350, 110, 30);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/InformationGUI.png"))); // NOI18N
        add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 400, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBtnActionPerformed
       LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "WoodMainScreen");
        }


// TODO add your handling code here:
    }//GEN-LAST:event_MenuBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackNextLbl;
    private javax.swing.JLabel BackgroundLbl;
    private javax.swing.JButton MenuBtn;
    private javax.swing.JLabel TitleLbl;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
