/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analogsection;
import java.awt.CardLayout;
import java.awt.LayoutManager;

/**
 *
 * @author John
 */
public class WoodQuizPanel extends javax.swing.JPanel {

    /**
     * Creates new form WoodQuizPanel
     */
    public WoodQuizPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLbl = new javax.swing.JLabel();
        HeadingLbl = new javax.swing.JLabel();
        QuestionTF = new javax.swing.JTextField();
        Ans3RBtn = new javax.swing.JRadioButton();
        Ans4RBtn = new javax.swing.JRadioButton();
        BackNextBtn = new javax.swing.JLabel();
        Ans1RBtn = new javax.swing.JRadioButton();
        SubmitBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BackgroundLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MenuBtn = new javax.swing.JButton();

        setLayout(null);

        TitleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TitleLbl.setForeground(new java.awt.Color(255, 255, 255));
        TitleLbl.setText("This is the section for the image quiz");
        add(TitleLbl);
        TitleLbl.setBounds(70, 20, 300, 22);

        HeadingLbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        HeadingLbl.setForeground(new java.awt.Color(255, 255, 255));
        HeadingLbl.setText("Question:");
        add(HeadingLbl);
        HeadingLbl.setBounds(90, 230, 80, 20);

        QuestionTF.setText("What type of tree is this?");
        add(QuestionTF);
        QuestionTF.setBounds(160, 220, 150, 30);

        Ans3RBtn.setText("Oak");
        add(Ans3RBtn);
        Ans3RBtn.setBounds(90, 260, 70, 23);

        Ans4RBtn.setText("Fern");
        Ans4RBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ans4RBtnActionPerformed(evt);
            }
        });
        add(Ans4RBtn);
        Ans4RBtn.setBounds(170, 260, 70, 23);

        BackNextBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\John\\Desktop\\resize.png")); // NOI18N
        BackNextBtn.setText("jLabel3");
        add(BackNextBtn);
        BackNextBtn.setBounds(40, 300, 120, 90);

        Ans1RBtn.setText("Chestnut");
        add(Ans1RBtn);
        Ans1RBtn.setBounds(260, 260, 70, 23);

        SubmitBtn.setBackground(new java.awt.Color(51, 153, 255));
        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });
        add(SubmitBtn);
        SubmitBtn.setBounds(200, 310, 130, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\John\\Desktop\\download (2).jpg")); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(90, 60, 270, 150);

        BackgroundLbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\John\\Desktop\\Wood-Background-Texture-452x336.jpg")); // NOI18N
        BackgroundLbl.setText("jLabel2");
        add(BackgroundLbl);
        BackgroundLbl.setBounds(0, 0, 450, 330);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\John\\Desktop\\Wood-Background-Texture-452x336.jpg")); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 330, 440, 80);

        MenuBtn.setText("Main Menu");
        MenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBtnActionPerformed(evt);
            }
        });
        add(MenuBtn);
        MenuBtn.setBounds(50, 330, 110, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBtnActionPerformed
           LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "WoodMainScreen");
        }
        



// TODO add your handling code here:
    }//GEN-LAST:event_MenuBtnActionPerformed

    private void Ans4RBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ans4RBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ans4RBtnActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_SubmitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Ans1RBtn;
    private javax.swing.JRadioButton Ans3RBtn;
    private javax.swing.JRadioButton Ans4RBtn;
    private javax.swing.JLabel BackNextBtn;
    private javax.swing.JLabel BackgroundLbl;
    private javax.swing.JLabel HeadingLbl;
    private javax.swing.JButton MenuBtn;
    private javax.swing.JTextField QuestionTF;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JLabel TitleLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    void setContentAreaFilled(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void setBorderPainted(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
