/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analogsection;

import java.awt.LayoutManager;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Stephen
 */
public class AnalogResistorCalcPanel extends javax.swing.JPanel {

    /**
     * Creates new form ResistorCalcPanel
     */
    private String selectedValue,band1,band2,band3,band4,valueTotal,minResistorValue, maxResistorValue,fileContents;
    

    ResistorCalc4Band calc;
    public AnalogResistorCalcPanel() {
        initComponents();
        this.setSize(400,450);
        selectedValue = "";
        band1 ="";
        band2 ="";
        band4 = "";
        calc = new ResistorCalc4Band();
        SaveBtn.setEnabled(false);
        ReadFileBtn.setEnabled(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        frstnumLbl = new javax.swing.JLabel();
        secondcolorLbl = new javax.swing.JLabel();
        thridcolorLbl = new javax.swing.JLabel();
        toloeranceLbl = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        anwserLbl = new javax.swing.JLabel();
        ResetBtn = new javax.swing.JButton();
        headingLbl = new javax.swing.JLabel();
        Color1CB = new javax.swing.JComboBox();
        Color2CB = new javax.swing.JComboBox();
        Color3CB = new javax.swing.JComboBox();
        ToloeranceCB = new javax.swing.JComboBox();
        TitleLbl = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        typesCB = new javax.swing.JComboBox();
        ReadFileBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setLayout(null);

        frstnumLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        frstnumLbl.setForeground(new java.awt.Color(255, 255, 255));
        frstnumLbl.setText("First color:");
        add(frstnumLbl);
        frstnumLbl.setBounds(50, 250, 90, 30);

        secondcolorLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        secondcolorLbl.setForeground(new java.awt.Color(255, 255, 255));
        secondcolorLbl.setText("Second color:");
        add(secondcolorLbl);
        secondcolorLbl.setBounds(50, 290, 90, 40);

        thridcolorLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        thridcolorLbl.setForeground(new java.awt.Color(255, 255, 255));
        thridcolorLbl.setText("Third color:");
        add(thridcolorLbl);
        thridcolorLbl.setBounds(260, 250, 90, 30);

        toloeranceLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        toloeranceLbl.setForeground(new java.awt.Color(255, 255, 255));
        toloeranceLbl.setText("Toloerance:");
        add(toloeranceLbl);
        toloeranceLbl.setBounds(260, 290, 80, 40);

        addBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        addBtn.setForeground(new java.awt.Color(0, 102, 255));
        addBtn.setText("Calculate");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn);
        addBtn.setBounds(0, 410, 100, 30);

        anwserLbl.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        anwserLbl.setForeground(new java.awt.Color(255, 255, 255));
        anwserLbl.setText(" = 365ohm");
        add(anwserLbl);
        anwserLbl.setBounds(120, 360, 270, 40);

        ResetBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        ResetBtn.setForeground(new java.awt.Color(0, 102, 255));
        ResetBtn.setText("Reset");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });
        add(ResetBtn);
        ResetBtn.setBounds(290, 410, 100, 30);

        headingLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        headingLbl.setForeground(new java.awt.Color(255, 255, 255));
        headingLbl.setText("Resistor Value:");
        add(headingLbl);
        headingLbl.setBounds(10, 340, 130, 30);

        Color1CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Black", "Brown", "Red", "Orange", "Yellow", "Green", "Blue", "Violet", "Grey", "White" }));
        add(Color1CB);
        Color1CB.setBounds(40, 270, 101, 30);

        Color2CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Black", "Brown", "Red", "Orange", "Yellow", "Green", "Blue", "Violet", "Grey", "White" }));
        add(Color2CB);
        Color2CB.setBounds(40, 320, 101, 27);

        Color3CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Black", "Brown", "Red", "Orange", "Yellow", "Green", "Blue", "Violet", "Grey", "Gold", "Silver" }));
        add(Color3CB);
        Color3CB.setBounds(250, 270, 101, 27);

        ToloeranceCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Brown", "Red", "Green", "Blue", "Violet", "Gold", "Silver", "None" }));
        add(ToloeranceCB);
        ToloeranceCB.setBounds(250, 320, 94, 27);

        TitleLbl.setFont(new java.awt.Font("Apple Chancery", 1, 19)); // NOI18N
        TitleLbl.setForeground(new java.awt.Color(255, 255, 255));
        TitleLbl.setText("Resistor value calculator ");
        add(TitleLbl);
        TitleLbl.setBounds(80, 0, 310, 30);

        exitBtn .setOpaque(false);
        exitBtn .setContentAreaFilled(false);
        exitBtn .setBorderPainted(false);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        add(exitBtn);
        exitBtn.setBounds(-3, -10, 80, 40);

        typesCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "4 Band", "5 Band", "6 Band" }));
        typesCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typesCBItemStateChanged(evt);
            }
        });
        add(typesCB);
        typesCB.setBounds(290, 0, 110, 30);

        ReadFileBtn.setForeground(new java.awt.Color(0, 102, 255));
        ReadFileBtn.setText("Read ");
        ReadFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadFileBtnActionPerformed(evt);
            }
        });
        add(ReadFileBtn);
        ReadFileBtn.setBounds(190, 410, 100, 29);

        SaveBtn.setForeground(new java.awt.Color(51, 102, 255));
        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        add(SaveBtn);
        SaveBtn.setBounds(100, 410, 75, 29);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/CalcGUI2.png"))); // NOI18N
        add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 610, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
        AnalogResistorCalcPanel reset = new AnalogResistorCalcPanel();
        anwserLbl.setText("");
        
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
         LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "AnalogMainScreen");
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void typesCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typesCBItemStateChanged
        // TODO add your handling code here:

        
        selectedValue = typesCB.getSelectedItem().toString();

        if(selectedValue.equals("4 Band")) {
            //display 4 band screen

            LayoutManager layout = getParent().getLayout();
            if (layout instanceof java.awt.CardLayout) {
                java.awt.CardLayout cl = (java.awt.CardLayout) layout;
                cl.show(getParent(), "AnalogCalcScreen");
            }
        } else if (selectedValue.equals("5 Band")) {
            //display 5 band screen
            LayoutManager layout = getParent().getLayout();
            if (layout instanceof java.awt.CardLayout) {
                java.awt.CardLayout cl = (java.awt.CardLayout) layout;
                cl.show(getParent(), "Analog5bandCalcScreen");
            }
        } else {
            //display 6 band screen
            LayoutManager layout = getParent().getLayout();
            if (layout instanceof java.awt.CardLayout) {
                java.awt.CardLayout cl = (java.awt.CardLayout) layout;
                cl.show(getParent(), "Analog6bandCalcScreen");
            }
        }
    
               
    }//GEN-LAST:event_typesCBItemStateChanged

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
         //selectedValue = typesCB.getSelectedItem().toString();
         // new instances of resistor4bandcalc 
        
         
         //clears label
         anwserLbl.setText("");
         
        SaveBtn.setEnabled(true);
        ReadFileBtn.setEnabled(true);
         
         //get the values selected in the GUI
         band1 = Color1CB.getSelectedItem().toString().toLowerCase();
         band2 = Color2CB.getSelectedItem().toString().toLowerCase();
         band3 = Color3CB.getSelectedItem().toString().toLowerCase();
         band4 = ToloeranceCB.getSelectedItem().toString().toLowerCase();
         //set the values to the instance of the class for proceesing 
         calc.setBand1(band1);
         calc.setBand2(band2);
         calc.setBand3(band3);
         calc.setBand4(band4);
         

         
         //Assign's the color codes a value
         calc.AssignValues();
         calc.AssignBand2Values();
         calc.assignMulitiplier();
         calc.assignToloerance();
         
         //calculate the resistors values
         calc.compute();
         
        
         calc.CalcToloerance();
        
         //get the max resistor value 
         calc.getMaxValue();
         
         //get the min rsistor value
        // calc.SaveToFile();
         
         //converts the values to kiloohmz
         calc.convertToKilohm();
         
         //retrive the calculations 
         valueTotal = calc.getValueResistor();
         
         maxResistorValue = calc.getMaxValue();
         
         minResistorValue = calc.getMinValue();
         
         anwserLbl.setText(valueTotal);
         
         JOptionPane.showMessageDialog(null,"Maximum Resistance Value:"+ " "+ maxResistorValue + "\n Minimum Resistance Value:"+ " "+  minResistorValue);
    }//GEN-LAST:event_addBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // saves the calculation to a file
         calc.SaveToFile();
         
        
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void ReadFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadFileBtnActionPerformed
       //reads the calculation from the file
         fileContents = calc.ReadFromFile();
         
         JOptionPane.showMessageDialog(null,"Saved calculations:"+"\n" +fileContents);
    }//GEN-LAST:event_ReadFileBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Color1CB;
    private javax.swing.JComboBox Color2CB;
    private javax.swing.JComboBox Color3CB;
    private javax.swing.JButton ReadFileBtn;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel TitleLbl;
    private javax.swing.JComboBox ToloeranceCB;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel anwserLbl;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel frstnumLbl;
    private javax.swing.JLabel headingLbl;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel secondcolorLbl;
    private javax.swing.JLabel thridcolorLbl;
    private javax.swing.JLabel toloeranceLbl;
    private javax.swing.JComboBox typesCB;
    // End of variables declaration//GEN-END:variables
}
