
package analogsection;

import java.awt.LayoutManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Stephen Kearns
 */
public class AnalogResistorCalc6band extends javax.swing.JPanel {

    /**
     * Creates new form AnalogResistorCalc6band
     */
    resistorBand6Calc calc;
    private String selectedValue,band1,band2,band3,band4,band5,band6,valueTotal,minResistorValue, maxResistorValue,tempco,fileContents;
    public AnalogResistorCalc6band() {
        initComponents();
        this.setSize(400,450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        value1CB = new javax.swing.JComboBox();
        Value2CB = new javax.swing.JComboBox();
        Value3CB = new javax.swing.JComboBox();
        Value1Lbl = new javax.swing.JLabel();
        Value2 = new javax.swing.JLabel();
        Value3 = new javax.swing.JLabel();
        Value4CB = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        Value5CB = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        Value6CB = new javax.swing.JComboBox();
        value5Lbl = new javax.swing.JLabel();
        headingLbl = new javax.swing.JLabel();
        anwserLbl = new javax.swing.JLabel();
        claculateBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        typesCB = new javax.swing.JComboBox();
        TitleLbl = new javax.swing.JLabel();
        SaveBtn = new javax.swing.JButton();
        ReadFileBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setLayout(null);

        value1CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Black", "Brown", "Red", "Orange", "Yellow", "Green", "Blue", "Violet", "Grey", "White" }));
        add(value1CB);
        value1CB.setBounds(10, 260, 100, 27);

        Value2CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Black", "Brown", "Red", "Orange", "Yellow", "Green", "Blue", "Violet", "Grey", "White" }));
        Value2CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Value2CBActionPerformed(evt);
            }
        });
        add(Value2CB);
        Value2CB.setBounds(140, 260, 101, 27);

        Value3CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Black", "Brown", "Red", "Orange", "Yellow", "Green", "Blue", "Violet", "Grey", "White", " " }));
        add(Value3CB);
        Value3CB.setBounds(270, 260, 101, 27);

        Value1Lbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        Value1Lbl.setForeground(new java.awt.Color(255, 255, 255));
        Value1Lbl.setText("First Value:");
        add(Value1Lbl);
        Value1Lbl.setBounds(20, 240, 80, 20);

        Value2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        Value2.setForeground(new java.awt.Color(255, 255, 255));
        Value2.setText("Second Value:");
        add(Value2);
        Value2.setBounds(140, 240, 100, 20);

        Value3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        Value3.setForeground(new java.awt.Color(255, 255, 255));
        Value3.setText("Third Value:");
        add(Value3);
        Value3.setBounds(270, 240, 90, 20);

        Value4CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Black", "Brown", "Red", "Orange", "Yellow", "Green", "Blue", "Violet", "Grey", "Gold ", "Silver" }));
        add(Value4CB);
        Value4CB.setBounds(10, 310, 101, 27);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fourth Value:");
        add(jLabel1);
        jLabel1.setBounds(20, 290, 100, 16);

        Value5CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Brown", "Red", "Green", "Blue", "Violet", "Grey", "Gold", "Silver", "None", " " }));
        add(Value5CB);
        Value5CB.setBounds(140, 310, 94, 27);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tolorence:");
        add(jLabel2);
        jLabel2.setBounds(150, 290, 80, 16);

        Value6CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Brown", "Red", "Green", "Blue", "Violet", "Grey", "Gold", "Silver", "None", " " }));
        add(Value6CB);
        Value6CB.setBounds(270, 310, 94, 27);

        value5Lbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        value5Lbl.setForeground(new java.awt.Color(255, 255, 255));
        value5Lbl.setText("Fifth Value:");
        add(value5Lbl);
        value5Lbl.setBounds(280, 290, 80, 16);

        headingLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        headingLbl.setForeground(new java.awt.Color(255, 255, 255));
        headingLbl.setText("Calulation:");
        add(headingLbl);
        headingLbl.setBounds(10, 340, 100, 16);

        anwserLbl.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        anwserLbl.setForeground(new java.awt.Color(255, 255, 255));
        anwserLbl.setText("= 1000 ohm");
        add(anwserLbl);
        anwserLbl.setBounds(90, 360, 240, 40);

        claculateBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        claculateBtn.setForeground(new java.awt.Color(0, 102, 255));
        claculateBtn.setText("Calulate");
        claculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claculateBtnActionPerformed(evt);
            }
        });
        add(claculateBtn);
        claculateBtn.setBounds(10, 400, 80, 40);

        ResetBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        ResetBtn.setForeground(new java.awt.Color(0, 102, 255));
        ResetBtn.setText("Reset");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });
        add(ResetBtn);
        ResetBtn.setBounds(290, 400, 90, 40);

        exitBtn .setOpaque(false);
        exitBtn .setContentAreaFilled(false);
        exitBtn .setBorderPainted(false);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        add(exitBtn);
        exitBtn.setBounds(0, 0, 75, 30);

        typesCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "4 Band", "5 Band", "6 Band" }));
        typesCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typesCBItemStateChanged(evt);
            }
        });
        add(typesCB);
        typesCB.setBounds(280, 0, 110, 30);

        TitleLbl.setFont(new java.awt.Font("Apple Chancery", 1, 19)); // NOI18N
        TitleLbl.setForeground(new java.awt.Color(255, 255, 255));
        TitleLbl.setText("Resistor value calculator ");
        add(TitleLbl);
        TitleLbl.setBounds(70, 0, 310, 30);

        SaveBtn.setForeground(new java.awt.Color(0, 102, 255));
        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        add(SaveBtn);
        SaveBtn.setBounds(100, 400, 80, 40);

        ReadFileBtn.setForeground(new java.awt.Color(0, 102, 255));
        ReadFileBtn.setText("Read Saved");
        ReadFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadFileBtnActionPerformed(evt);
            }
        });
        add(ReadFileBtn);
        ReadFileBtn.setBounds(190, 400, 90, 40);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/Calc6band.png"))); // NOI18N
        add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 390, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void Value2CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Value2CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Value2CBActionPerformed

    private void typesCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typesCBItemStateChanged
        // TODO add your handling code here:

        String selectedValue;
        selectedValue = typesCB.getSelectedItem().toString();

        if (selectedValue.equals("4 Band")) {
            //display 4 band screen

            LayoutManager layout = getParent().getLayout();
            if (layout instanceof java.awt.CardLayout) {
                java.awt.CardLayout cl = (java.awt.CardLayout) layout;
                cl.show(getParent(), "AnalogCalcScreen");
            }
        } else if (selectedValue.equals("5 Band")) {
            //display 5 band screen
            LayoutManager layout = getParent().getLayout();
            if (layout instanceof java.awt.CardLayout) {
                java.awt.CardLayout cl = (java.awt.CardLayout) layout;
                cl.show(getParent(), "Analog5bandCalcScreen");
            }
        } else {
            //display 6 band screen
            LayoutManager layout = getParent().getLayout();
            if (layout instanceof java.awt.CardLayout) {
                java.awt.CardLayout cl = (java.awt.CardLayout) layout;
                cl.show(getParent(), "Analog6bandCalcScreen");
            }
        }

    }//GEN-LAST:event_typesCBItemStateChanged

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "AnalogMainScreen");
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
        AnalogResistorCalcPanel reset = new AnalogResistorCalcPanel();
        anwserLbl.setText("");
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void claculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claculateBtnActionPerformed
        // TODO add your handling code here:
          // new instances of resistor4bandcalc 
       //  ResistorCalc6band calc = new ResistorCalc6band();
        calc = new resistorBand6Calc(band1,band2, band3, band4, band5);
         //clears label
         anwserLbl.setText("");
         
         //get the values selected in the GUI
         band1 = value1CB.getSelectedItem().toString().toLowerCase();
         band2 = Value2CB.getSelectedItem().toString().toLowerCase();
         band3 = Value3CB.getSelectedItem().toString().toLowerCase();
         band4 = Value4CB.getSelectedItem().toString().toLowerCase();
         band5 = Value5CB.getSelectedItem().toString().toLowerCase();
         band6 = Value6CB.getSelectedItem().toString().toLowerCase();
         //set the values to the instance of the class for proceesing 
         calc.setBand1(band1);
         calc.setBand2(band2);
         calc.setBand3(band3);
         calc.setBand4(band4);
         calc.setBand5(band5);
         calc.setBand6(band6);
         
         
         //Assign's the color codes a value
         calc.AssignValues();
         calc.AssignBand2Values();
         calc.AssignBand3();
         calc.assignMulitiplier();
         calc.assignToloerance();
         calc.assignTempcoValue();
         
         //calculate the resistors values
         calc.compute();
         
        
         calc.CalcToloerance();
        
         //get the max resistor value 
         calc.getMaxValue();
         
         //get the min rsistor value
         
         
         //converts the values to kiloohmz
         calc.convertToKilohm();
         
         //retrive the calculations 
         valueTotal = calc.getValueResistor();
         
         maxResistorValue = calc.getMaxValue();
         
         minResistorValue = calc.getMinValue();
         tempco = calc.getTempco();
         anwserLbl.setText(valueTotal);
         
         JOptionPane.showMessageDialog(null,"Maximum Resistance Value:"+ " "+ maxResistorValue + "\n Minimum Resistance Value:"+ " "+  minResistorValue +"\n"+tempco);
    }//GEN-LAST:event_claculateBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
         // saves the calculation to a file
         calc.SaveToFile();
         
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void ReadFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadFileBtnActionPerformed
         //reads the calculation from the file
         fileContents = calc.ReadFromFile();
         
         JOptionPane.showMessageDialog(null,"Saved calculations:"+"\n" +fileContents);
    }//GEN-LAST:event_ReadFileBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReadFileBtn;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel TitleLbl;
    private javax.swing.JLabel Value1Lbl;
    private javax.swing.JLabel Value2;
    private javax.swing.JComboBox Value2CB;
    private javax.swing.JLabel Value3;
    private javax.swing.JComboBox Value3CB;
    private javax.swing.JComboBox Value4CB;
    private javax.swing.JComboBox Value5CB;
    private javax.swing.JComboBox Value6CB;
    private javax.swing.JLabel anwserLbl;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton claculateBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel headingLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox typesCB;
    private javax.swing.JComboBox value1CB;
    private javax.swing.JLabel value5Lbl;
    // End of variables declaration//GEN-END:variables
}
