/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analogsection;

import static analogsection.Information.infoType;
import java.awt.CardLayout;
import java.awt.FlowLayout;
import java.awt.LayoutManager;
import javax.swing.JPanel;

/**
 *
 * @author Stephen kearns
 */
public class DigitalSectionGUI extends javax.swing.JPanel {
   
    /**
     * Creates new form AnalogGUI
     */
 
    public DigitalSectionGUI() {
        initComponents();
        this.setSize(400,450);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HangmanBtn = new javax.swing.JButton();
        QuizBtn = new javax.swing.JButton();
        InfoBtn = new javax.swing.JButton();
        CalcBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(400, 450));
        setLayout(null);

        HangmanBtn.setBackground(new java.awt.Color(0, 102, 204));
        HangmanBtn.setText("Hangman");
        HangmanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HangmanBtnActionPerformed(evt);
            }
        });
        add(HangmanBtn);
        HangmanBtn.setBounds(120, 260, 150, 30);

        QuizBtn.setBackground(new java.awt.Color(0, 102, 204));
        QuizBtn.setText("Quiz");
        QuizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizBtnActionPerformed(evt);
            }
        });
        add(QuizBtn);
        QuizBtn.setBounds(120, 200, 150, 30);

        InfoBtn.setBackground(new java.awt.Color(0, 102, 204));
        InfoBtn.setText("Information");
        InfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoBtnActionPerformed(evt);
            }
        });
        add(InfoBtn);
        InfoBtn.setBounds(110, 140, 150, 30);

        CalcBtn.setBackground(new java.awt.Color(0, 102, 204));
        CalcBtn.setText("Previous Menu");
        CalcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcBtnActionPerformed(evt);
            }
        });
        add(CalcBtn);
        CalcBtn.setBounds(100, 320, 150, 30);

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/exit.png"))); // NOI18N
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        add(exitBtn);
        exitBtn.setBounds(350, 10, 40, 40);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/hassanimg.jpg"))); // NOI18N
        add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 400, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void QuizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizBtnActionPerformed
        // TODO add your handling code here:
        //declare and initilize dig
        DigitalQuiz dig = new DigitalQuiz();
        //call chosse randomRandomQuestion
        dig.choseRandomQuestion();
        //enter quiz screen
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "QuizScreen");
        }
    }//GEN-LAST:event_QuizBtnActionPerformed

    private void InfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoBtnActionPerformed
        // TODO add your handling code here:
        
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "DigitalInformationScreen");
        }
    }//GEN-LAST:event_InfoBtnActionPerformed

    private void HangmanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HangmanBtnActionPerformed
        // TODO add your handling code here:
        DigitalQuiz dig = new DigitalQuiz();
        dig.choseRandomQuestion();
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "DigitalHangMan");
        }
    }//GEN-LAST:event_HangmanBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        //exits application
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void CalcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "MAIN");
        }
    }//GEN-LAST:event_CalcBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalcBtn;
    private javax.swing.JButton HangmanBtn;
    private javax.swing.JButton InfoBtn;
    private javax.swing.JButton QuizBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton exitBtn;
    // End of variables declaration//GEN-END:variables
}
