/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analogsection;

import java.awt.LayoutManager;

/**
 *
 * @author Sean
 */
public class DigitalHangMan extends javax.swing.JPanel {

    /**
     * Creates new form AnalogHangmanPanel
     */
    public DigitalHangMan() {
        initComponents();
        this.setSize(400,450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingLbl = new javax.swing.JLabel();
        sentanceLbl = new javax.swing.JLabel();
        anwserTF = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        BackgroundLbl = new javax.swing.JLabel();

        setLayout(null);

        headingLbl.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        headingLbl.setForeground(new java.awt.Color(0, 102, 255));
        headingLbl.setText("Fill in the missing word in the sentance:");
        add(headingLbl);
        headingLbl.setBounds(10, 310, 280, 20);

        sentanceLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        sentanceLbl.setText("Most hated first programming application is hello__ ");
        add(sentanceLbl);
        sentanceLbl.setBounds(10, 260, 370, 40);
        add(anwserTF);
        anwserTF.setBounds(20, 340, 310, 50);

        Submit.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        Submit.setForeground(new java.awt.Color(0, 102, 255));
        Submit.setText("Submit anwser");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        add(Submit);
        Submit.setBounds(100, 400, 170, 30);

        jLabel1.setFont(new java.awt.Font("Apple Chancery", 1, 18)); // NOI18N
        jLabel1.setText("Hangman Game");
        add(jLabel1);
        jLabel1.setBounds(140, 0, 170, 40);

        exitBtn .setOpaque(false);
        exitBtn .setContentAreaFilled(false);
        exitBtn .setBorderPainted(false);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        add(exitBtn);
        exitBtn.setBounds(0, 0, 60, 40);

        BackgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/HangmanGUI.png"))); // NOI18N
        add(BackgroundLbl);
        BackgroundLbl.setBounds(0, 0, 400, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "DigitalSectionScreen");
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLbl;
    private javax.swing.JButton Submit;
    private javax.swing.JTextField anwserTF;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel headingLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel sentanceLbl;
    // End of variables declaration//GEN-END:variables
}
