/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analogsection;


import static analogsection.Information.infoType;
import java.awt.CardLayout;
import java.awt.FlowLayout;
import java.awt.LayoutManager;
import javax.swing.JPanel;

/**
 *
 * @author Stephen kearns
 */
public class DigitalInformationGUI extends javax.swing.JPanel {

    /**
     * Creates new form AnalogGUI
     */
 
    public DigitalInformationGUI() {
        initComponents();
        this.setSize(400,450);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Infobtn = new javax.swing.JButton();
        Componentbtn = new javax.swing.JButton();
        truthbtn = new javax.swing.JButton();
        DiagnosticBtn = new javax.swing.JButton();
        prevbtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(400, 450));
        setLayout(null);

        Infobtn.setBackground(new java.awt.Color(0, 102, 204));
        Infobtn.setText("General");
        Infobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfobtnActionPerformed(evt);
            }
        });
        add(Infobtn);
        Infobtn.setBounds(90, 70, 150, 30);

        Componentbtn.setBackground(new java.awt.Color(0, 102, 204));
        Componentbtn.setText("Components");
        Componentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComponentbtnActionPerformed(evt);
            }
        });
        add(Componentbtn);
        Componentbtn.setBounds(110, 140, 150, 30);

        truthbtn.setBackground(new java.awt.Color(0, 102, 204));
        truthbtn.setText("Truth Tables");
        truthbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truthbtnActionPerformed(evt);
            }
        });
        add(truthbtn);
        truthbtn.setBounds(120, 210, 150, 30);

        DiagnosticBtn.setBackground(new java.awt.Color(0, 102, 204));
        DiagnosticBtn.setText("Diagnostic Tools");
        DiagnosticBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiagnosticBtnActionPerformed(evt);
            }
        });
        add(DiagnosticBtn);
        DiagnosticBtn.setBounds(110, 280, 150, 30);

        prevbtn.setBackground(new java.awt.Color(0, 102, 204));
        prevbtn.setText("previous Menu");
        prevbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevbtnActionPerformed(evt);
            }
        });
        add(prevbtn);
        prevbtn.setBounds(90, 350, 150, 30);

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/exit.png"))); // NOI18N
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        add(exitBtn);
        exitBtn.setBounds(350, 10, 40, 40);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/hassanimg.jpg"))); // NOI18N
        add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 400, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void ComponentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComponentbtnActionPerformed
        // TODO add your handling code here:
        infoType = 8;
        
    
        Information.InfoType(infoType);
        
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "AnalogInfoScreen");
        }
    }//GEN-LAST:event_ComponentbtnActionPerformed

    private void truthbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truthbtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "DigitalTruthTables");
        }
    }//GEN-LAST:event_truthbtnActionPerformed

    private void InfobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfobtnActionPerformed
        // TODO add your handling code here:
       
         infoType = 2;
         //it retrives an array from the information class
        //and populates it with analog general questions
      
        Information.InfoType(infoType);
      //  Information.setCount(count);
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            //cl.show(getParent(), "DigitalGen");
            cl.show(getParent(), "AnalogInfoScreen");
        }
    }//GEN-LAST:event_InfobtnActionPerformed

    private void DiagnosticBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiagnosticBtnActionPerformed
        // TODO add your handling code here:
        infoType = 9;
        
    
        Information.InfoType(infoType);
        
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "AnalogInfoScreen");
        }
    }//GEN-LAST:event_DiagnosticBtnActionPerformed

    private void prevbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevbtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "DigitalSectionScreen");
        }
    }//GEN-LAST:event_prevbtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Componentbtn;
    private javax.swing.JButton DiagnosticBtn;
    private javax.swing.JButton Infobtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton prevbtn;
    private javax.swing.JButton truthbtn;
    // End of variables declaration//GEN-END:variables
}
