/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analogsection;

import java.awt.LayoutManager;

/**
 *
 * @author magui_000
 */
public class PlasticQuizGUI extends javax.swing.JPanel {

    /**
     * Creates new form PlasticQuizGUI
     */
    public PlasticQuizGUI() {
        initComponents();
        this.setSize(400,450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLbl = new javax.swing.JLabel();
        AHeadingLbl = new javax.swing.JLabel();
        HeadingLbl = new javax.swing.JLabel();
        QuestionTF = new javax.swing.JTextField();
        Ans1RBtn = new javax.swing.JRadioButton();
        Ans3RBtn = new javax.swing.JRadioButton();
        Ans4RBtn = new javax.swing.JRadioButton();
        SubmitBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ExitBtn = new javax.swing.JButton();

        setLayout(null);

        TitleLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TitleLbl.setForeground(new java.awt.Color(255, 255, 255));
        TitleLbl.setText("Plastic Quiz");
        add(TitleLbl);
        TitleLbl.setBounds(140, 10, 140, 22);

        AHeadingLbl.setText("Choose one of the following answer's:");
        add(AHeadingLbl);
        AHeadingLbl.setBounds(20, 210, 190, 16);

        HeadingLbl.setText("Question:");
        add(HeadingLbl);
        HeadingLbl.setBounds(20, 130, 60, 16);

        QuestionTF.setText("What Type of Plastic is used to make a Bottle cap?");
        add(QuestionTF);
        QuestionTF.setBounds(10, 150, 380, 50);

        Ans1RBtn.setText("PvC");
        add(Ans1RBtn);
        Ans1RBtn.setBounds(190, 320, 90, 23);

        Ans3RBtn.setText("PvB");
        add(Ans3RBtn);
        Ans3RBtn.setBounds(190, 240, 93, 23);

        Ans4RBtn.setText("PvG");
        add(Ans4RBtn);
        Ans4RBtn.setBounds(190, 280, 90, 23);

        SubmitBtn.setBackground(new java.awt.Color(51, 153, 255));
        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });
        add(SubmitBtn);
        SubmitBtn.setBounds(120, 370, 130, 40);

        exitBtn .setOpaque(false);
        exitBtn .setContentAreaFilled(false);
        exitBtn .setBorderPainted(false);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        add(exitBtn);
        exitBtn.setBounds(-3, -10, 80, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/QuizGUI3.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 440);

        ExitBtn.setText("jButton1");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        add(ExitBtn);
        ExitBtn.setBounds(0, 10, 97, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "PlasticMainScreen");
    }//GEN-LAST:event_ExitBtnActionPerformed
    }
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "PlasticMainScreen");
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_SubmitBtnActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AHeadingLbl;
    private javax.swing.JRadioButton Ans1RBtn;
    private javax.swing.JRadioButton Ans3RBtn;
    private javax.swing.JRadioButton Ans4RBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JLabel HeadingLbl;
    private javax.swing.JTextField QuestionTF;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JLabel TitleLbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
